demo/apps/home/urls.py
from django.urls import re_path
from . import views
from . import apps


app_name = apps.HomeConfig.name

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
]

demo/apps/user/urls.py
from django.urls import path, re_path
from . import views


app_name = 'user'

urlpatterns = [
    path('deconnexion/', views.deconnexion, name='deconnexion'),
    path('connexion/', views.connexion, name='connexion'),
    re_path(r'^nonautorise$', views.nonautorise, name='nonautorise'),
    ]

demo/demo/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^user/", include("user.urls", namespace="user")),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(
        r"^", include("home.urls", namespace="home")
    ),  # positionner toujours en dernier !
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        re_path(r"^__debug__/", include(debug_toolbar.urls)),
        path("__reload__/", include("django_browser_reload.urls")),
    ] + urlpatterns

demo/apps/home/models.py
from django.db import models
from django.dispatch import receiver
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.db.models.signals import post_delete, pre_save
from demo.settings import MEDIA_URL
from demo.media_file_cleaning import auto_delete_file_on_delete, auto_delete_file_on_change
from . import apps




def default_image_url():
    """
    retourne l'url de l'image par défaut
    """
    try:
        default_content = get_object_or_404(DefaultContent, description="default_image")
        return default_content.image.url.replace(MEDIA_URL, '/')
    except (Http404, ValueError):
        return "static/img/img_default.svg"


class DefaultContent(models.Model):
    """
    contenu par défaut (notamment pour les images) 
    """
    description = models.CharField(max_length=50, default='')
    explication = models.TextField(blank=True)
    contenu = models.TextField(blank=True)
    image = models.ImageField(upload_to="home/images/", null=True, blank=True)
    fichier = models.FileField(upload_to="home/files/", null=True, blank=True) 

    class Meta:
        app_label = apps.HomeConfig.label
        verbose_name = "Contenu par défaut"

    def __str__(self):
        return self.description

    def get_file(self):
        """ liste des fichiers media, pour gérer leur mise à jour et suppression """
        return [self.image, self.fichier ]
    
    @classmethod
    def create(cls, **kwargs):
        newinstance = "déjà existant"
        try:
            cls.objects.get(description=kwargs["description"])
        except cls.DoesNotExist:
            newinstance = "vient d'être créé"
            instance = cls(**kwargs)
            instance.save()
        print('   DefaultContent {} : ok - {}'.format( kwargs["description"], newinstance))
   

class Libelles(models.Model):
    """
    contenu qui sera transmis au template pour affichage de la page 
    """
    description = models.CharField(max_length=50, default='')
    explication = models.TextField(blank=True)
    contenu = models.TextField(blank=True)
    image = models.ImageField(upload_to="home/images/", null=True, blank=True)
    fichier = models.FileField(upload_to="home/files/", null=True, blank=True) 
    lien = models.URLField(blank=True) 

    class Meta:
        verbose_name = "libellé"

    def __str__(self):
        return self.description

    def get_file(self):
        """ liste des fichiers media, pour gérer leur mise à jour et suppression """
        return [self.image, self.fichier ]

    @classmethod
    def create(cls, **kwargs):
        newinstance = "déjà existant"
        try:
            cls.objects.get(description=kwargs["description"])
        except cls.DoesNotExist:
            newinstance = "vient d'être créé"
            instance = cls(**kwargs)
            instance.save()
        print('   Libelles {} : ok - {}'.format( kwargs["description"], newinstance))           


# Suppression des fichiers MEDIAROOT inutiles lors de la mise à jour ou suppression
@receiver(post_delete, sender=Libelles)
def auto_delete_miniatures_on_delete(sender, instance, **kwargs):
    auto_delete_file_on_delete(sender, instance) 

@receiver(pre_save, sender=Libelles)
def auto_delete_miniatures_on_change(sender, instance, **kwargs):
    auto_delete_file_on_change(sender, instance) 

demo/apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser



class User(AbstractUser):
    pass

    def __str__(self):
        return "{} {} [{}]".format(self.last_name, self.first_name, self.username)

demo/apps/home/forms.py
from django import forms


class PromptForm(forms.Form):
    prompt = forms.CharField(
        label="",
        max_length=1000,
        widget=forms.Textarea(attrs={"class": "prompt"}),
    )

    class Meta:
        widgets = {}

demo/apps/user/forms.py
from django import forms


class ConnexionForm(forms.Form):
    username = forms.CharField(
        label="Nom de login ",
        max_length=30,
        widget=forms.TextInput(attrs={"class": "inputbox"}),
    )
    password = forms.CharField(
        label="Mot de passe ", widget=forms.PasswordInput(attrs={"class": "inputbox"})
    )

    class Meta:
        widgets = {}

demo/apps/home/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .context import usercontext
from .forms import PromptForm
from .output import sentiment_classifier, text_gen


@login_required
def index(request):
    context = usercontext(request)
    context.update(
        {
            "titre_onglet": "Démo",
            "response": "",
            "request": False,
        }
    )
    form = PromptForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        prompt = form.cleaned_data["prompt"]
        response = text_gen(prompt)
        context.update({"prompt": prompt, "response": response, "request": True})

    context.update({"form": form})

    return render(request, "home/index.html", context)

demo/apps/user/views.py
# from authlib.integrations.django_client import OAuth

from django.shortcuts import render, redirect
from django.http import Http404
from django.contrib.auth import authenticate, login, logout
from django.core import management
from django.core.exceptions import PermissionDenied

from demo.settings import DEBUG
from home.models import Libelles
from .forms import ConnexionForm


def deconnexion(request):
    logout(request)
    return redirect("home:index")


def connexion(request):
    """
    Vue permettant de se connecter
    """

    # suppression des sessions expirées :
    management.call_command("clearsessions")

    context = {lib.description: lib for lib in Libelles.objects.all()}
    context.update(
        {
            "titre_onglet": "connexion",
            "authentication_fail": False,
        }
    )
    if request.method == "POST":
        form = ConnexionForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
            else:
                context.update({"authentication_fail": True})

    form = ConnexionForm()
    context.update({"form": form})

    return render(request, "user/connexion.html", context)


def nonautorise(request):
    raise PermissionDenied

demo/apps/home/templates/home/index.html
{% extends 'base.html' %}

{% load static template_tags %}

{% block header %}
{% endblock %}

{% block content %}
    <section id="accueilflex flex-col" class="reachable">
        <div class="mt-6 p-4 flex flex-col justify-center items-start bg-slate-200">
            <div id="titre" class="mb-2 ">
                <h1 class="text-sm font-bold sm:text-lg">{{Accueil_titre|find_content:10}}</h1>
            </div>
            <div id="description" class="text-sm">
                <p>{{Accueil_description|find_content:150}}</p>
            </div>
        </div>
        <div class="mt-6 p-4 flex flex-col justify-center items-start">            
            <form class="flex flex-col items-center" method="post" action=".">
                {% csrf_token %}
            
                {% if request %}
                    <div class="mt-10 flex flex-col gap-4">
                        <p class="prompt">{{ prompt }}</p>
                        <p class="response">{{ response}}</p>
                    </div>
                    <a class="mt-10 action-button" href="{% url 'home:index' %}">Recommencer</a>

                {% else %}
                    <div class="mt-10 flex flex-col gap-4">
                        <p>Posez votre question :</p>
                        {{ form }}
                    </div>
                    <button type="submit" class="mt-10 action-button">Envoyer</button>
                {% endif %}
            </form>

        </div>
    </section>


{% endblock %}

demo/apps/user/templates/user/connexion.html
{% extends 'base.html'%}

{% load static template_tags %}

{% block content %}

<section class="mt-10 flex flex-col items-center">

        <h3>Entrez vos informations de connexion :</h3>

        <form class="flex flex-col items-center" method="post" action=".">
            {% csrf_token %}
            {% if authentication_fail %}
                <p class="mt-4 text-red-500 font-bold">Utilisateur inconnu ou mauvais de mot de passe.</p>
            {% endif %}
            {% if user.is_authenticated %}
                <p>Vous êtes connecté, {{ user.username }} !</p>
                <p><a class="action-button" href="{% url 'user:deconnexion' %}">Se déconnecter</a></p>
            {% else %}
                <div class="mt-10 flex flex-col gap-4">
                    {{ form.as_p }}
                </div>
                <button type="submit" class="mt-10 action-button">Se connecter</button>
            {% endif %}
        </form>
    
</section>

{% endblock %}

demo/templates/alert_box.html
<div id="{{alert}}" class="hidden alert-box fixed z-50 m-auto inset-0 p-8 w-5/6 max-w-lg h-40 flex flex-col justify-between bg-slate-50">
    <p class="text-sm sm:text-base text-slate-800">{{message}}</p>
    <div class="mt-8 flex flex-row justify-between">
        <button id="back-button" class="annuler grey-button min-w-32">{{back_text}}</button>
        <button class="{{act_button}} no-underline red-button min-w-32">{{act_text}}</button>
        <a href="{{ link }}" class="{{act_link}} red-button min-w-32">{{act_text}}</a>
    </div>
</div>

demo/templates/base.html
<!DOCTYPE html>
{% load static tailwind_tags template_tags%}
<html lang="fr" class="scroll-smooth">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta charset="utf-8" />
        {% tailwind_css %}
        <link rel="shortcut icon" type="image/png" href="{{ Favicon|find_img }}" />
        <link rel="apple-touch-icon" sizes="180x180" href="{{ Favicon|find_img }}" />
        <title>{{titre_onglet}}</title>
        <meta name="robots" content="index,follow">
        <script type="module" src="{% static 'js/deconnect.js' %}"></script>
        {% block header %}
        {% endblock %}
    </head>
    <body class="m-0 p-0 font-sans text-slate-700 bg-slate-100">
        
        <div class="w-full min-w-screen-xs min-h-screen flex flex-col justify-start items-center">
            
            <header class="fixed z-10 pl-8 pr-12 h-16 w-full flex flex-row justify-between items-center bg-margin text-white sm:h-20">
                <div id="logo">
                    <a href="{% url 'home:index' %}#accueil">
                        <img class="h-12 sm:h-16" src="{{ Bandeau_logo|find_file }}" alt="{{ Bandeau_logo|find_content:1 }}" />
                    </a>
                </div>
               
                <div id="navbar" class="flex flex-row justify-between items-center gap-4 sm:gap-8">
                

                    <div id="navbar" class="flex flex-row justify-between items-center gap-4 sm:gap-4">
                
                        <a href="{% url 'home:index' %}" class="">
                                <img class="h-8" src="{% static 'img/home_white.svg' %}" />
                        </a>
                        
                        <a href="{% url 'user:connexion' %}" title="connectez-vous !" class="text-sm m-0 p-0 w-8 h-8 border-white border-2 bg-transparent rounded-full text-center flex justify-center items-center" style="color:transparent; text-shadow: 0 0 0 #fff;">{{user|initiales}}</a>
                        
                        <a id="deconnect-button" class="group hover:cursor-pointer" >
                            <img class="h-8 group-hover:hidden" src="{% static 'img/deconnexion_white.svg' %}" />  
                            <img class="h-8 hidden group-hover:inline" src="{% static 'img/deconnexion_red.svg' %}" />
                        </a>
                    </div>
                                              
            </header>


            <main class="mt-20 mb-12 px-6 max-w-6xl w-full flex flex-col justify-between items-center"> 
                {% block content %}{% endblock %}
            </main>
            <footer class="w-full mt-auto px-16 py-4 bg-margin text-slate-200">
                <h2 class="text-md font-bold"> {{ Footer_description|find_content:30 }} </h2>
                <ul class="flex flex-row justify-center items-center gap-4">
                    {% if Lien_1|find_file != "" %}
                    <li>
                        <a href="{{ Lien_1.lien }}" target=_blank >
                            <img class="w-10 h-10" src="{{ Lien_1|find_file }}" alt="{{ Lien_1.contenu }}"/>
                        </a>
                    </li>
                    {% endif %}
                    {% if Lien_2|find_file != "" %}
                    <li>
                        <a href="{{ Lien_2.lien }}" target=_blank >
                            <img class="w-10 h-10" src="{{ Lien_2|find_file }}" alt="{{ Lien_2.contenu }}"/>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            {% if user.is_staff %}
                <div class="mt-4 flex flex-row justify-center sm:justify-end">
                    <a href="/admin/" class="action-button">Administration du site</a> 
                </div>
            {% endif %}
            </footer>
        </div>
        <div id="shadow-mask" class="hidden fixed z-20 w-full top-0 left-0 h-full bg-black opacity-50"></div>

        {% include "alert_box.html" with alert="alert-deconnect" message="Voulez-vous vraiment vous déconnecter ?" act_button="hidden" act_link="link" link="/user/deconnexion" back_text="Annuler" act_text="Se déconnecter" %}

        {% if debug %}
        {# Utilitaire affichant les tailles d'écran - masqué en production #}
        <div class="fixed z-30 bottom-4 left-4 bg-slate-300 p-1 rounded font-bold">
            <span class="sm:hidden">XS</span>
            <span class="hidden sm:block md:hidden">SM</span>
            <span class="hidden md:block lg:hidden">MD</span>
            <span class="hidden lg:block xl:hidden">LG</span>
            <span class="hidden xl:block 2xl:hidden">XL</span>
            <span class="hidden 2xl:block 3xl:hidden">2XL</span>
            <span class="hidden 3xl:block ">3XL+</span>
        </div>
        {% endif %}
        
    </body>
</html>

demo/theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Django Tailwind</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% tailwind_css %}
</head>

<body class="bg-gray-50 text-black font-serif leading-normal tracking-normal">

    <div class="toast toast-top toast-end">
        <div class="alert alert-info">
            <span>Hello from daisyUi 👋</span>
        </div>
    </div>

<div class="container mx-auto">
    <section class="flex items-center justify-center h-screen">
        <h1 class="text-5xl">Django + Tailwind = ❤️</h1>
    </section>
</div>
</body>
</html>